config/routes.rb
Rails.application.routes.draw do
  root "messages#index"
  resources :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
    # 必須入力、20文字以上
    validates :name, length: { maximum: 20 }, presence: true
    # 必須入力、2文字以上,30文字以下
    validates :body, length: { minimum: 2, maximun: 30 }, presence: true
    # 0以上の数字
    validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update,:destroy]
  
  def index
    @message = Message.new
    @messages = Message.all
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      # redirect_toは301でブラウザに別のURLへアクセスさせる
      redirect_to root_path, notice: "メッセージを保存しました"
    else
      @messages = Message.all
      # flash.nowは同じアクセスでflashを使う
      flash.now[:alert] = "メッセージの保存に失敗しました"
      # htmlを返すだけ
      render 'index'
    end
  end 
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      redirect_to root_path, notice: "メッセージの更新に成功しました！"  
    else
      flash.now[:alert] = "メッセージの更新に失敗しました"
      render "edit"
    end
  end
  
  def destroy
    @message.destroy
    redirect_to root_path, notice: "メッセージを削除しました"
  end
  
  private
    # 保存系でPOSTした内容を元にする場合は項目を制御する
    def message_params
      params.require(:message).permit(:name, :age, :body)
    end
    
    def set_message
      @message = Message.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container-fluid">
      <div class="container-inner">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= root_path %>">Message Board</a>
        </div>
      </div>
    </div>
  </nav>
  <div class="container-fluid">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message, html: {class: "form-horizontal"}) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <li>
        <%= @message.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
        </li>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
      <%= f.label :name, '名前', class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.text_field :name, class: "form-control", placeholder: '名前' %>
      </div>
  </div>
  <div class="form-group">
      <%= f.label :age, '年齢', class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
         <%= f.text_field :age, class: "form-control", type: "number", placeholder: "年齢" %>
      </div>
  </div>
  <div class="form-group">
      <%= f.label :body, '内容', class: "col-sm-1 control-label" %>
      <div class="col-sm-11">
        <%= f.text_area :body, class: "form-control", placeholder: "メッセージ内容" %>      
      </div>
  </div>
  <div class="form-group">
      <div class="col-sm-1"></div>
      <div class="col-sm-11">
        <div class="btn-wrap">
          <%= f.submit "送信する", class: "btn btn-success" %>
        </div>
      </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div class="container-inner">
    <h3>メッセージの編集</h1>
    <%= render 'form' %>
</div>

app/views/messages/index.html.erb
<div class="container-inner">
  <div class="panel panel-default">
      <div class="panel-heading">
          メッセージ一覧
      </div>
      <div class="panel-body">
          <% @messages.each do |message| %>
            <span class="label label-info">
                <%= message.name %> <%= message.age %>歳
            </span>
            <span>
                <%= message.body %>
                (<%= link_to "編集", edit_message_path(message) %>)
                (<%= link_to "削除", message, method: :delete, data: { confirm: "削除してもよろしいですか？" } %>)
            </span>
            <br>
          <% end %>
      </div>
  </div>
  <%= render 'form' %>
</div>